a = 5
b = 4
print("a + b =",a + b) # Addition +
print("a - b =",a - b) # Subtraction -
print("a * b =",a * b) # Multiplication *
print("a / b =",a / b) # Division /
print("a % b =",a % b) # Modulus %
print("a ** b =",a ** b) # Exponentiation **
print("a // b =",a // b) # Floor Division //